services:
  db:
    image: postgres:13
    restart: always
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=arlo
      - POSTGRES_PASSWORD=arlo
      - POSTGRES_DB=arlo
      - PGUSER=arlo
    profiles: [dev]


  dev:
    build:     
      dockerfile: Dockerfile.dev
    # TODO: Figure out putting the worker in its own container
    command: >
      bash -c "PORT=8080 poetry run python -m noauth &
      poetry run python -m server.main &
      poetry run python -m server.worker.worker &
      yarn --cwd client start --host"
    ports:
      - 3000:3000
      - 3001:3001
      - 8080:8080
    depends_on:
      db: 
        condition: service_healthy
    environment:
      - FLASK_APP=server/__init__.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://arlo:arlo@db:5432/arlo
    profiles: [dev]
 


    # TODO: prod profiles 

volumes:
  postgres_data:
